# Generated by Django 6.0 on 2025-12-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='place',
            new_name='place_name',
        ),
    ]
