# Generated by Django 6.0 on 2025-12-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_designation',
            old_name='designation',
            new_name='designation_name',
        ),
    ]
