# Generated by Django 6.0 on 2026-01-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_serviceprovidertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_serviceprovidertype')),
            ],
        ),
    ]
