# Generated by Django 6.0 on 2026-01-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_tbl_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_providerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_amount', models.IntegerField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_services')),
            ],
        ),
    ]
