# Generated by Django 6.0 on 2026-01-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_providerservice',
            old_name='service',
            new_name='service_name',
        ),
        migrations.AlterField(
            model_name='tbl_providerservice',
            name='provider_amount',
            field=models.IntegerField(),
        ),
    ]
