# Generated by Django 6.0 on 2026-01-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0003_tbl_workgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_workgallery',
        ),
    ]
