# Generated by Django 6.0 on 2026-01-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0005_tbl_workgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_providerservice',
        ),
    ]
