# Generated by Django 6.0 on 2026-01-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_services'),
        ('Guest', '0008_rename_serviceprovidertype_name_tbl_serviceprovider_serviceprovidertype'),
        ('Serviceprovider', '0006_delete_tbl_providerservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_providerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_amount', models.IntegerField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_services')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
            ],
        ),
    ]
