# Generated by Django 6.0 on 2026-01-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0007_tbl_providerservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_providerservice',
        ),
    ]
