# Generated by Django 6.0 on 2026-01-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_services'),
        ('Serviceprovider', '0008_delete_tbl_providerservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_providerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_amount', models.IntegerField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_services')),
            ],
        ),
    ]
