# Generated by Django 6.0 on 2026-02-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0009_tbl_providerservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_workgallery',
        ),
    ]
