# Generated by Django 6.0 on 2026-02-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_serviceprovider'),
        ('Serviceprovider', '0010_delete_tbl_workgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.CharField(max_length=50)),
                ('work_photo', models.FileField(upload_to='Assets/WorkDocs/')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
            ],
        ),
    ]
