# Generated by Django 6.0 on 2026-03-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0013_tbl_providerservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_providerservice',
        ),
    ]
