# Generated by Django 6.0 on 2026-03-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_services'),
        ('Guest', '0012_tbl_serviceprovider'),
        ('Serviceprovider', '0014_delete_tbl_providerservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_providerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_amount', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_services')),
            ],
        ),
    ]
