# Generated by Django 6.0 on 2025-12-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser_name', models.CharField(max_length=50)),
                ('newuser_gender', models.CharField(max_length=10)),
                ('newuser_contact', models.CharField(max_length=15)),
                ('newuser_email', models.CharField(max_length=15)),
                ('newuser_password', models.CharField(max_length=15)),
                ('newuser_address', models.CharField(max_length=15)),
                ('newuser_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('newuser_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
