# Generated by Django 6.0 on 2025-12-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_employee'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_contact', models.CharField(max_length=15)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_password', models.CharField(max_length=30)),
                ('seller_establishdate', models.DateField(max_length=12)),
                ('seller_licenseno', models.CharField(max_length=15)),
                ('seller_ownername', models.CharField(max_length=50)),
                ('seller_licenseproof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('seller_ownerproof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
