# Generated by Django 6.0 on 2026-01-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_serviceprovidertype'),
        ('Guest', '0004_tbl_newuser_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_name', models.CharField(max_length=50)),
                ('serviceprovider_email', models.CharField(max_length=30)),
                ('serviceprovider_contact', models.CharField(max_length=15)),
                ('serviceprovider_address', models.CharField(max_length=15)),
                ('serviceprovider_photo', models.FileField(upload_to='Assets/SellerDocs/')),
                ('serviceprovider_idproof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('serviceprovider_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('serviceprovidertype_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_serviceprovidertype')),
            ],
        ),
    ]
