# Generated by Django 6.0 on 2026-01-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_serviceprovider',
        ),
    ]
