# Generated by Django 6.0 on 2026-01-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_serviceprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_serviceprovider',
            old_name='serviceprovidertype_name',
            new_name='serviceprovidertype',
        ),
    ]
