# Generated by Django 6.0 on 2026-02-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_rename_serviceprovidertype_name_tbl_serviceprovider_serviceprovidertype'),
        ('Serviceprovider', '0010_delete_tbl_workgallery'),
        ('User', '0016_remove_tbl_profit_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_serviceprovider',
        ),
    ]
