# Generated by Django 6.0 on 2026-02-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_serviceprovider',
        ),
    ]
