# Generated by Django 6.0 on 2026-02-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_services'),
        ('Guest', '0011_delete_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_name', models.CharField(max_length=50)),
                ('serviceprovider_email', models.CharField(max_length=30)),
                ('serviceprovider_contact', models.CharField(max_length=15)),
                ('serviceprovider_address', models.CharField(max_length=15)),
                ('serviceprovider_photo', models.FileField(upload_to='Assets/SellerDocs/')),
                ('serviceprovider_idproof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('serviceprovider_certificate', models.FileField(upload_to='Assets/SellerDocs/')),
                ('serviceprovider_password', models.CharField(max_length=30)),
                ('serviceprovider_status', models.IntegerField(default=0)),
                ('serviceprovider_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('serviceprovidertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_serviceprovidertype')),
            ],
        ),
    ]
