# Generated by Django 6.0 on 2026-01-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_request',
            old_name='request_fromdate',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_todate',
            field=models.DateField(),
        ),
    ]
