# Generated by Django 6.0 on 2026-01-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_request_fromdate_tbl_request_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
