# Generated by Django 6.0 on 2026-01-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_rename_serviceprovidertype_name_tbl_serviceprovider_serviceprovidertype'),
        ('User', '0007_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='serviceprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider'),
        ),
    ]
