# Generated by Django 6.0 on 2026-02-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_profit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_profit',
        ),
    ]
