# Generated by Django 6.0 on 2026-02-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_rename_serviceprovidertype_name_tbl_serviceprovider_serviceprovidertype'),
        ('User', '0010_delete_tbl_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_amount', models.IntegerField(default=0)),
                ('profit_date', models.DateField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
