# Generated by Django 6.0 on 2026-02-04 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rating',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
