# Generated by Django 6.0 on 2026-02-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_profit',
            name='request',
        ),
        migrations.RemoveField(
            model_name='tbl_profit',
            name='serviceprovider',
        ),
        migrations.RemoveField(
            model_name='tbl_profit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='serviceprovider',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='service',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='serviceprovider',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_profit',
        ),
        migrations.DeleteModel(
            name='tbl_rating',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
