# Generated by Django 6.0 on 2026-02-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0012_tbl_serviceprovider'),
        ('User', '0016_remove_tbl_profit_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=10)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=50, null=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('serviceprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
