# Generated by Django 6.0 on 2026-02-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_services'),
        ('Guest', '0012_tbl_serviceprovider'),
        ('User', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_amount', models.IntegerField(default=0)),
                ('request_bill', models.FileField(upload_to='Assets/RequestDocs/')),
                ('request_todate', models.DateField()),
                ('request_details', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_services')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
